"use client";

import type { ScenarioMetrics } from "@/types/dashboard";
import MetricCard from "@/components/ui/MetricCard";
import { formatBillions } from "@/lib/calculations";

interface Props {
  metrics: ScenarioMetrics;
}

export default function MetricsCards({ metrics }: Props) {
  const cashEquivalent = metrics.treasuryDemandBillions + metrics.cashHoldingsBillions;

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      <MetricCard
        label="US Treasury Demand"
        value={formatBillions(metrics.treasuryDemandBillions)}
        sub={`Active: ${metrics.scenarioLabel}`}
        accent="bg-blue-50"
        tooltip={{
          description: "Estimated demand for US Treasuries generated by fiat-backed stablecoins, based on the active scenario's market cap and your reserve composition.",
          rows: [
            { label: "Market cap", value: formatBillions(metrics.marketCapBillions) },
            { label: "Treasury reserve %", value: `${((metrics.treasuryDemandBillions / metrics.marketCapBillions) * 100).toFixed(1)}%` },
            { label: "= Treasury demand", value: formatBillions(metrics.treasuryDemandBillions) },
          ],
        }}
      />
      <MetricCard
        label="% of $27T Treasury Market"
        value={`${metrics.treasuryDemandAsShareOfMarket.toFixed(3)}%`}
        sub="Share of outstanding"
        accent="bg-indigo-50"
        tooltip={{
          description: "How large stablecoin-driven Treasury demand is relative to the total ~$27 trillion of US Treasuries currently outstanding.",
          rows: [
            { label: "Treasury demand", value: formatBillions(metrics.treasuryDemandBillions) },
            { label: "Total outstanding", value: "$27.0T" },
            { label: "= Market share", value: `${metrics.treasuryDemandAsShareOfMarket.toFixed(3)}%` },
          ],
        }}
      />
      <MetricCard
        label="Stablecoin Market Cap"
        value={formatBillions(metrics.marketCapBillions)}
        sub="Total supply"
        accent="bg-emerald-50"
        tooltip={{
          description: "Total fiat-backed USD stablecoin supply for the active scenario. Adjust scenarios in the input panel to model different market sizes.",
          rows: [
            { label: "Scenario", value: metrics.scenarioLabel },
            { label: "Treasury demand", value: formatBillions(metrics.treasuryDemandBillions) },
            { label: "Cash holdings", value: formatBillions(metrics.cashHoldingsBillions) },
            { label: "Corp bonds", value: formatBillions(metrics.corpBondsBillions) },
            { label: "Other", value: formatBillions(metrics.otherBillions) },
          ],
        }}
      />
      <MetricCard
        label="Cash-Equivalent Holdings"
        value={formatBillions(cashEquivalent)}
        sub="Treasuries + Cash"
        accent="bg-amber-50"
        tooltip={{
          description: "Sum of US Treasury and cash holdings — the most liquid portion of reserves, often used as a proxy for systemic liquidity impact.",
          rows: [
            { label: "US Treasuries", value: formatBillions(metrics.treasuryDemandBillions) },
            { label: "Cash & equivalents", value: formatBillions(metrics.cashHoldingsBillions) },
            { label: "= Cash-equivalent", value: formatBillions(cashEquivalent) },
            { label: "% of market cap", value: `${((cashEquivalent / metrics.marketCapBillions) * 100).toFixed(1)}%` },
          ],
        }}
      />
    </div>
  );
}
